---
- name: 'Deploy app in kubernetes'
  hosts: nodes
  become: yes
  user: root
  ignore_errors: yes
  tasks:
  - name: 'Creating deployment'
    command: 'kubectl create deployment myapp --image=dhanrajranvirkar/myapp:"{{ docker_tag }}"'
  - name: 'Creating service of type NodePort'
    command: 'kubectl expose deployment myapp --type=NodePort --target-port=8080 --port=80'
